ExpensesControlApp/Models/ErrorViewModel.cs
namespace ExpensesControlApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ExpensesControlApp/Models/Expenses/Expense.cs
using System.ComponentModel.DataAnnotations;

namespace ExpensesControlApp.Models.Expenses
{
    public class Expense
    {
        [Key]
        public int Id { get; set; }

        [MaxLength(100)]
        public string Description { get; set; }

        public double Value { get; set; }

        public DateTime Date { get; set; }
    }
}

ExpensesControlApp/Controllers/ExpenseController.cs
using ExpensesControlApp.DTOs;
using ExpensesControlApp.Models;
using ExpensesControlApp.Services;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ExpensesControlApp.Controllers
{
    public class ExpenseController : Controller
    {
        private readonly ILogger<ExpenseController> _logger;
        private readonly IExpenseService _expenseService;

        public ExpenseController(ILogger<ExpenseController> logger, IExpenseService expenseService)
        {
            _logger = logger;
            _expenseService = expenseService;
        }

        public async Task<IActionResult> Index()
        {
            var listExpenseDTO = new ListExpenseDTO();
            listExpenseDTO.Items = await _expenseService.FindBy(listExpenseDTO.InitialDate, listExpenseDTO.FinalDate);

            return View(listExpenseDTO);
        }

        [HttpPost]
        public async Task<IActionResult> Index(ListExpenseDTO listExpenseDTO)
        {
            try
            {
                listExpenseDTO.Items = await _expenseService.FindBy(listExpenseDTO.InitialDate, listExpenseDTO.FinalDate);

                return View(listExpenseDTO);
            }
            catch (Exception e)
            {

                ModelState.AddModelError("CustomError", e.Message);
                return View(listExpenseDTO);
            }
        }

        public async Task<IActionResult> Create()
        {
            var createExpenseDTO = new CreateExpenseDTO();

            return View(createExpenseDTO);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateExpenseDTO createExpenseDTO)
        {
            try
            {
                await _expenseService.Create(createExpenseDTO);

                return RedirectToAction("Index");
            }
            catch (Exception e)
            {

                ModelState.AddModelError("CustomError", e.Message);
                return View(createExpenseDTO);
            }
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ExpensesControlApp/Views/Expense/Create.cshtml
@model ExpensesControlApp.DTOs.CreateExpenseDTO

<form method="post">
    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="row">
        <div class="col-md-12">
            <div class="form-group">
                <input asp-for="Description" placeholder="Enter the description" class="form-control" />
            </div>
        </div>
    </div>
    </br>
    <div class="row">
        <div class="col-md-12">
            <div class="form-group">
                <input asp-for="Value" type="number" placeholder="Enter the value" class="form-control" />
            </div>
        </div>
    </div>
    </br>
    <div class="row">
        <div class="col-md-12">
            <div class="form-group">
                <input asp-for="Date" type="date" placeholder="Enter the date" class="form-control" />
            </div>
        </div>
    </div>
    </br>
    <div class="row">
        <div class="col-md-12">
            <div class="d-grid">
                <a asp-action="Index" class="btn btn-secondary btn-login text-uppercase fw-bold">Go back</a>
            </div>
        </div>
    </div>
    </br>
    <div class="row">
        <div class="col-md-12">
            <div class="d-grid">
                <button type="submit" class="btn btn-primary btn-login text-uppercase fw-bold">Create</button>
            </div>
        </div>
    </div>
</form>

ExpensesControlApp/Views/Expense/Index.cshtml
@model ExpensesControlApp.DTOs.ListExpenseDTO

@{
    ViewData["Title"] = "Home Page";
}

<div class="row">
    <div class="col-sm">
        <h1>Expenses</h1>
    </div>
</div>

<div class="row">
    <div class="col-sm-12">
        <a asp-action="Create" asp-controller="Expense" class="btn btn-primary btn-block">New expense</a>
    </div>
</div>

<form method="post">
    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="row">
        <div class="col-sm-4">
            <div class="form-group">
                <input asp-for="InitialDate" type="date" placeholder="Enter the start date" class="form-control" />
            </div>
        </div>
        <div class="col-sm-4">
            <div class="form-group">
                <input asp-for="FinalDate" type="date" placeholder="Enter the end date" class="form-control" />
            </div>
        </div>
        <div class="col-sm-4">
            <div class="form-group">
                <button type="submit" class="btn btn-primary">Search</button>
            </div>
        </div>
    </div>
</form>

<div class="row">
    <div class="col-md">
        <table class="table">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Description</th>
                    <th>Value</th>
                    <th>Date</th>
                </tr>
            </thead>
            <tbody>
                @if (Model.Items.Count > 0)
                {
                    foreach (var item in Model.Items)
                    {
                        <tr>
                            <td>@item.Id</td>
                            <td>@item.Description</td>
                            <td>@item.Value</td>
                            <td>@item.Date.ToString("dd/MM/yyyy")</td>
                        </tr>
                    }
                }
                else 
                {
                    <tr><td colspan="4">No record found</td></tr>
                }
            </tbody>
        </table>
    </div>
</div>

ExpensesControlApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ExpensesControlApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ExpensesControlApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Expense" asp-action="Index">ExpensesControlApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Expense" asp-action="Index">Home</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ExpensesControlApp
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.12/jquery.validate.unobtrusive.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>